services:

  # MariaDB
  mariadb:
    ports:
      - '${FORWARD_DB_PORT:-3306}:3306'
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    volumes:
      - 'mariadb:/var/lib/mysql'

  # Websockets
  soketi:
    environment:
      SOKETI_DEBUG: '1'
      SOKETI_METRICS_SERVER_PORT: '9601'
    ports:
      - '${SOKETI_METRICS_SERVER_PORT:-9601}:9601'

volumes:
  sail-mariadb:
    driver: local