services:

    # App
    app:
        container_name: '${CONTAINER_NAME}'
        build:
            dockerfile: Dockerfile
            context: docker
        image: '${CONTAINER_NAME}'
        working_dir: /var/www
        environment:
            LARAVEL_SAIL: 1
            IGNITION_LOCAL_SITES_PATH: '${PWD}'
        volumes:
            - './:/var/www/'
        networks:
            - sail

    # Database
    mariadb:
        container_name: '${CONTAINER_NAME}-mariadb'
        image: 'mariadb:10'
        environment:
            MYSQL_ROOT_PASSWORD: '${DB_PASSWORD}'
            MYSQL_ROOT_HOST: '%'
            MYSQL_DATABASE: '${DB_DATABASE}'
            MYSQL_USER: '${DB_USERNAME}'
            MYSQL_PASSWORD: '${DB_PASSWORD}'
            TZ: "Europe/Rome"
        networks:
            - sail
        healthcheck:
            test:
                - CMD
                - mysqladmin
                - ping
                - '-p${DB_PASSWORD}'
            retries: 3
            timeout: 5s

#    # Websockets
#    soketi:
#        container_name: '${CONTAINER_NAME}-soketi'
#        image: 'quay.io/soketi/soketi:latest-16-alpine'
#        environment:
#            - TZ=Europe/Rome
#        networks:
#            - sail
networks:
    sail:
        driver: bridge
