services:

  # Proxy server
  caddy:
    image: caddy:latest
    container_name: '${CONTAINER_NAME}-caddy'
    networks:
      - sail
    ports:
      - '${APP_PORT}:80'
      - "443:443"
    volumes:
      - './:/var/www'
      - './docker/Caddyfile:/etc/caddy/Caddyfile'